name = "onedrive"

[namespace.storage]

[namespace.storage.new]
required = ["credential"]
optional = ["work_dir"]

[namespace.storage.op.create]
optional = ["object_mode"]

[namespace.storage.op.delete]
optional = ["object_mode"]

[namespace.storage.op.list]
optional = ["list_mode", "continuation_token"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size"]

[namespace.storage.op.stat]
optional = ["object_mode"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback", "description"]

[pairs.description]
type = "string"
description = "description for target file/dir"
