// Code generated by go generate internal/cmd; DO NOT EDIT.
package types

import (
	"fmt"
)

// Field index in storageMeta bit
const (
	storageMetaIndexLocation = 1 << 0
	storageMetaIndexName     = 1 << 1
	storageMetaIndexWorkDir  = 1 << 2
)

type StorageMeta struct {
	location string
	Name     string
	WorkDir  string

	// bit used as a bitmap for object value, 0 means not set, 1 means set
	bit uint64
	m   map[string]interface{}
}

func (m *StorageMeta) GetLocation() (string, bool) {
	if m.bit&storageMetaIndexLocation != 0 {
		return m.location, true
	}
	return "", false
}

func (m *StorageMeta) MustGetLocation() string {
	if m.bit&storageMetaIndexLocation == 0 {
		panic(fmt.Sprintf("storage-meta location is not set"))
	}
	return m.location
}

func (m *StorageMeta) SetLocation(v string) *StorageMeta {
	m.location = v
	m.bit |= storageMetaIndexLocation
	return m
}
func (m *StorageMeta) GetName() string {
	return m.Name
}

func (m *StorageMeta) SetName(v string) *StorageMeta {
	m.Name = v
	return m
}
func (m *StorageMeta) GetWorkDir() string {
	return m.WorkDir
}

func (m *StorageMeta) SetWorkDir(v string) *StorageMeta {
	m.WorkDir = v
	return m
}
