name = "uss"

[namespace.storage]
implement = ["direr"]

[namespace.storage.new]
required = ["name", "credential"]
optional = ["storage_features", "default_storage_pairs", "work_dir", "http_client_options"]

[namespace.storage.op.create]
optional = ["object_mode"]

[namespace.storage.op.delete]
optional = ["object_mode"]

[namespace.storage.op.list]
optional = ["list_mode", "continuation_token"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size"]

[namespace.storage.op.stat]
optional = ["object_mode"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback"]

[pairs.storage_features]
type = "StorageFeatures"
description = "set storage features"

[pairs.default_storage_pairs]
type = "DefaultStoragePairs"
description = "set default pairs for storager actions"
