name = "s3"

[namespace.service]

[namespace.service.new]
required = ["credential"]
optional = [ "endpoint", "http_client_options", "force_path_style", "use_accelerate", "use_arn_region"]

[namespace.service.op.create]
required = ["location"]

[namespace.service.op.delete]
optional = ["location", "excepted_bucket_owner"]

[namespace.service.op.get]
optional = ["location"]

[namespace.storage]
features = ["virtual_dir", "virtual_link"]
implement = ["direr", "linker", "multiparter", "storage_http_signer", "multipart_http_signer"]

[namespace.storage.new]
required = ["location", "name"]
optional = ["work_dir"]

[namespace.storage.op.create]
optional = ["multipart_id", "object_mode"]

[namespace.storage.op.create_dir]
optional = ["excepted_bucket_owner", "storage_class"]

[namespace.storage.op.delete]
optional = ["excepted_bucket_owner", "multipart_id", "object_mode"]

[namespace.storage.op.list]
optional = ["list_mode", "excepted_bucket_owner"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size", "excepted_bucket_owner", "server_side_encryption_customer_algorithm", "server_side_encryption_customer_key"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback", "storage_class", "excepted_bucket_owner", "server_side_encryption_bucket_key_enabled", "server_side_encryption_customer_algorithm", "server_side_encryption_customer_key", "server_side_encryption_aws_kms_key_id", "server_side_encryption_context", "server_side_encryption"]

[namespace.storage.op.stat]
optional = ["excepted_bucket_owner", "multipart_id", "object_mode", "server_side_encryption_customer_algorithm", "server_side_encryption_customer_key"]

[namespace.storage.op.create_multipart]
optional = ["server_side_encryption_bucket_key_enabled", "excepted_bucket_owner", "server_side_encryption_customer_algorithm", "server_side_encryption_customer_key", "server_side_encryption_aws_kms_key_id", "server_side_encryption_context", "server_side_encryption"]

[namespace.storage.op.write_multipart]
optional = ["excepted_bucket_owner", "server_side_encryption_customer_algorithm", "server_side_encryption_customer_key", "io_callback"]

[namespace.storage.op.list_multipart]
optional = ["excepted_bucket_owner"]

[namespace.storage.op.complete_multipart]
optional = ["excepted_bucket_owner"]

[namespace.storage.op.query_sign_http_read]
optional = ["excepted_bucket_owner", "offset", "size", "server_side_encryption_customer_algorithm", "server_side_encryption_customer_key"]

[namespace.storage.op.query_sign_http_write]
optional = ["content_md5", "content_type", "excepted_bucket_owner", "storage_class", "server_side_encryption_bucket_key_enabled", "server_side_encryption_customer_algorithm", "server_side_encryption_customer_key", "server_side_encryption_aws_kms_key_id", "server_side_encryption_context", "server_side_encryption"]

[namespace.storage.op.query_sign_http_delete]
optional = ["multipart_id", "excepted_bucket_owner", "object_mode"]

[pairs.service_features]
type = "ServiceFeatures"
description = "set service features"

[pairs.default_service_pairs]
type = "DefaultServicePairs"
description = "set default pairs for service actions"

[pairs.force_path_style]
type = "bool"
description = "see http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html for Amazon S3: Virtual Hosting of Buckets"

[pairs.disable_100_continue]
type = "bool"
description = "set this to `true` to disable the SDK adding the `Expect: 100-Continue` header to PUT requests over 2MB of content"

[pairs.use_accelerate]
type = "bool"
description = "set this to `true` to enable S3 Accelerate feature"

[pairs.use_arn_region]
type = "bool"
description = "set this to `true` to have the S3 service client to use the region specified in the ARN, when an ARN is provided as an argument to a bucket parameter"

[pairs.storage_features]
type = "StorageFeatures"
description = "set storage features"

[pairs.default_storage_pairs]
type = "DefaultStoragePairs"
description = "set default pairs for storager actions"

[pairs.storage_class]
type = "string"
defaultable = true

[pairs.server_side_encryption_bucket_key_enabled]
type = "bool"
description = "specifies whether Amazon S3 should use an S3 Bucket Key for object encryption with server-side encryption using AWS KMS (SSE-KMS)"

[pairs.excepted_bucket_owner]
type = "string"
description = "the account ID of the excepted bucket owner"

[pairs.server_side_encryption_customer_algorithm]
type = "string"
description = "specifies the algorithm to use to when encrypting the object. The header value must be `AES256`."

[pairs.server_side_encryption_customer_key]
type = "[]byte"
description = "specifies the customer-provided encryption key for Amazon S3 to use to encrypt/decrypt the source object. It must be 32-byte AES-256 key."

[pairs.server_side_encryption_aws_kms_key_id]
type = "string"
description = "specifies the AWS KMS key ID to use for object encryption"

[pairs.server_side_encryption_context]
type = "string"
description = "specifies the AWS KMS Encryption Context to use for object encryption. The value of this header is a base64-encoded UTF-8 string holding JSON with the encryption context key-value pairs."

[pairs.server_side_encryption]
type = "string"
description = "the server-side encryption algorithm used when storing this object in Amazon"

[infos.object.meta.storage-class]
type = "string"

[infos.object.meta.server-side-encryption]
type = "string"

[infos.object.meta.server-side-encryption-customer-algorithm]
type = "string"

[infos.object.meta.server-side-encryption-aws-kms-key-id]
type = "string"

[infos.object.meta.server-side-encryption-context]
type = "string"

[infos.object.meta.server-side-encryption-customer-key-md5]
type = "string"

[infos.object.meta.server-side-encryption-bucket-key-enabled]
type = "bool"
