name = "cos"

[namespace.service]

[namespace.service.new]
required = ["credential"]
optional = ["endpoint", "http_client_options"]

[namespace.service.op.create]
required = ["location"]

[namespace.service.op.delete]
required = ["location"]

[namespace.service.op.get]
required = ["location"]

[namespace.storage]
features = ["virtual_dir"]
implement = ["multiparter", "direr"]

[namespace.storage.new]
required = ["name", "location"]
optional = ["work_dir"]

[namespace.storage.op.create]
optional = ["multipart_id", "object_mode"]

[namespace.storage.op.create_dir]
optional = ["storage_class"]

[namespace.storage.op.delete]
optional = ["multipart_id", "object_mode"]

[namespace.storage.op.list]
optional = ["list_mode"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size", "server_side_encryption_customer_algorithm", "server_side_encryption_customer_key"]

[namespace.storage.op.stat]
optional = ["multipart_id", "object_mode", "server_side_encryption_customer_algorithm", "server_side_encryption_customer_key"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback", "storage_class", "server_side_encryption_customer_algorithm", "server_side_encryption_customer_key", "server_side_encryption", "server_side_encryption_cos_kms_key_id", "server_side_encryption_context"]

[namespace.storage.op.create_multipart]
optional = ["content_type", "storage_class", "server_side_encryption_customer_algorithm", "server_side_encryption_customer_key", "server_side_encryption", "server_side_encryption_cos_kms_key_id", "server_side_encryption_context"]

[namespace.storage.op.write_multipart]
optional = ["content_md5"]

[pairs.storage_class]
type = "string"

[pairs.server_side_encryption_customer_algorithm]
type = "string"
description = "specifies the algorithm to use to when encrypting the object. Now only `AES256` is supported."

[pairs.server_side_encryption_customer_key]
type = "[]byte"
description = "specifies the customer-provided encryption key to encrypt/decrypt the source object. It must be a 32-byte AES-256 key."

[pairs.server_side_encryption_cos_kms_key_id]
type = "string"
description = "specifies the COS KMS key ID to use for object encryption."

[pairs.server_side_encryption_context]
type = "string"
description = "specifies the COS KMS Encryption Context to use for object encryption. The value of this header is a base64-encoded UTF-8 string holding JSON with the encryption context key-value pairs."

[pairs.server_side_encryption]
type = "string"
description = "the server-side encryption algorithm used when storing this object. It can be `AES-256` for SSE-COS, and `cos/kms` for SSE-KMS."

[infos.object.meta.storage-class]
type = "string"

[infos.object.meta.server-side-encryption]
type = "string"

[infos.object.meta.server-side-encryption-cos-kms-key-id]
type = "string"

[infos.object.meta.server-side-encryption-customer-algorithm]
type = "string"

[infos.object.meta.server-side-encryption-customer-key-md5]
type = "string"
