[loose_pair]
virtual = true
namespaces = ["service", "storage"]
description = """
loose_pair feature is designed for users who don't want strict pair checks.

If this feature is enabled, the service will not return an error for not support pairs.

This feature was introduced in GSP-109.
"""

[virtual_dir]
virtual = true
namespaces = ["storage"]
description = """
virtual_dir feature is designed for a service that doesn't have native dir support but wants to provide simulated operations.

- If this feature is disabled (the default behavior), the service will behave like it doesn't have any dir support.
- If this feature is enabled, the service will support simulated dir behavior in create_dir, create, list, delete, and so on.

This feature was introduced in GSP-109.
"""

[virtual_object_metadata]
virtual = true
namespaces = ["storage"]
description = """
virtual_object_metadata feature is designed for a service that doesn't have native object metadata support but wants to provide simulated operations.

- If this feature is disabled (the default behavior), the service will behave like it doesn't have any object metadata support.
- If this feature is enabled, the service will support simulated object metadata behavior in the list, stat, and so on.

This feature was introduced in GSP-109.
"""

[virtual_link]
virtual = true
namespaces = ["storage"]
description = """
virtual_link feature is designed for a service that doesn't have native support for link.

- If this feature is enabled, the service will run compatible mode: create link via native methods, but allow read link from old-style link object.
- If this feature is not enabled, the service will run in native as other service.

This feature was introduced in GSP-86.
"""

[write_empty_object]
namespaces = ["storage"]
description = """
write_empty_object feature is designed for a service that support write empty object.

This behavior was defined in GSP-751 and classified as an operation-related feature in GSP-837.
"""
