[bi]
type = "*types.BlockIterator"

[bid]
type = "string"

[bids]
type = "[]string"

[dst]
type = "string"

[err]
type = "error"

[expire]
type = "time.Duration"

[index]
type = "int"

[meta]
type = "*types.StorageMeta"

[n]
type = "int64"

[name]
type = "string"

[o]
type = "*types.Object"

[offset]
type = "int64"

[oi]
type = "*types.ObjectIterator"

[op]
type = "string"

[pairs]
type = "...types.Pair"

[part]
type = "*types.Part"

[parts]
type = "[]*types.Part"

[path]
type = "string"

[pi]
type = "*types.PartIterator"

[r]
type = "io.Reader"

[req]
type = "*http.Request"

[serviceFeatures]
type = "types.ServiceFeatures"

[size]
type = "int64"

[src]
type = "string"

[sti]
type = "*types.StoragerIterator"

[storageFeatures]
type = "types.StorageFeatures"

[store]
type = "types.Storager"

[url]
type = "string"

[w]
type = "io.Writer"

[target]
type = "string"
