[bi]
package = "types"
type = "*BlockIterator"

[bid]
type = "string"

[bids]
type = "[]string"

[dst]
type = "string"

[err]
type = "error"

[expire]
package = "time"
type = "Duration"

[index]
type = "int"

[meta]
package = "types"
type = "*StorageMeta"

[n]
type = "int64"

[name]
type = "string"

[o]
package = "types"
type = "*Object"

[offset]
type = "int64"

[oi]
package = "types"
type = "*ObjectIterator"

[op]
type = "string"

[pairs]
package = "types"
type = "...Pair"

[part]
package = "types"
type = "*Part"

[parts]
package = "types"
type = "[]*Part"

[path]
type = "string"

[pi]
package = "types"
type = "*PartIterator"

[r]
package = "io"
type = "Reader"

[req]
package = "http"
type = "*Request"

[srvf]
package = "types"
type = "ServiceFeatures"

[size]
type = "int64"

[src]
type = "string"

[sti]
package = "types"
type = "*StoragerIterator"

[stof]
package = "types"
type = "StorageFeatures"

[store]
package = "types"
type = "Storager"

[url]
type = "string"

[w]
package = "io"
type = "Writer"

[target]
type = "string"
