// Code generated by go generate via internal/cmd/meta; DO NOT EDIT.
package posixfs

import (
	"github.com/Xuanwo/storage/types"
)

// StoragerType is the storager type for posixfs
const StoragerType = types.StoragerType("posixfs")

var allowedStoragePairs = map[string]map[string]struct{}{
	"delete": {
		"recursive": struct{}{},
	},
	"init": {
		"work_dir": struct{}{},
	},
	"list_dir": {
		"recursive": struct{}{},
	},
	"read": {
		"offset": struct{}{},
		"size":   struct{}{},
	},
	"write": {
		"size": struct{}{},
	},
}

var allowedServicePairs = map[string]map[string]struct{}{}

type pairStorageDelete struct {
	HasRecursive bool
	Recursive    bool
}

func parseStoragePairDelete(opts ...*types.Pair) (*pairStorageDelete, error) {
	result := &pairStorageDelete{}

	values := make(map[string]interface{})
	for _, v := range opts {
		if _, ok := allowedStoragePairs["delete"]; !ok {
			continue
		}
		if _, ok := allowedStoragePairs["delete"][v.Key]; !ok {
			continue
		}
		values[v.Key] = v.Value
	}
	var v interface{}
	var ok bool
	v, ok = values[types.Recursive]
	if ok {
		result.HasRecursive = true
		result.Recursive = v.(bool)
	}
	return result, nil
}

type pairStorageInit struct {
	HasWorkDir bool
	WorkDir    string
}

func parseStoragePairInit(opts ...*types.Pair) (*pairStorageInit, error) {
	result := &pairStorageInit{}

	values := make(map[string]interface{})
	for _, v := range opts {
		if _, ok := allowedStoragePairs["init"]; !ok {
			continue
		}
		if _, ok := allowedStoragePairs["init"][v.Key]; !ok {
			continue
		}
		values[v.Key] = v.Value
	}
	var v interface{}
	var ok bool
	v, ok = values[types.WorkDir]
	if !ok {
		return nil, types.NewErrPairRequired(types.WorkDir)
	}
	if ok {
		result.HasWorkDir = true
		result.WorkDir = v.(string)
	}
	return result, nil
}

type pairStorageListDir struct {
	HasRecursive bool
	Recursive    bool
}

func parseStoragePairListDir(opts ...*types.Pair) (*pairStorageListDir, error) {
	result := &pairStorageListDir{}

	values := make(map[string]interface{})
	for _, v := range opts {
		if _, ok := allowedStoragePairs["list_dir"]; !ok {
			continue
		}
		if _, ok := allowedStoragePairs["list_dir"][v.Key]; !ok {
			continue
		}
		values[v.Key] = v.Value
	}
	var v interface{}
	var ok bool
	v, ok = values[types.Recursive]
	if ok {
		result.HasRecursive = true
		result.Recursive = v.(bool)
	}
	return result, nil
}

type pairStorageRead struct {
	HasOffset bool
	Offset    int64
	HasSize   bool
	Size      int64
}

func parseStoragePairRead(opts ...*types.Pair) (*pairStorageRead, error) {
	result := &pairStorageRead{}

	values := make(map[string]interface{})
	for _, v := range opts {
		if _, ok := allowedStoragePairs["read"]; !ok {
			continue
		}
		if _, ok := allowedStoragePairs["read"][v.Key]; !ok {
			continue
		}
		values[v.Key] = v.Value
	}
	var v interface{}
	var ok bool
	v, ok = values[types.Offset]
	if ok {
		result.HasOffset = true
		result.Offset = v.(int64)
	}
	v, ok = values[types.Size]
	if ok {
		result.HasSize = true
		result.Size = v.(int64)
	}
	return result, nil
}

type pairStorageWrite struct {
	HasSize bool
	Size    int64
}

func parseStoragePairWrite(opts ...*types.Pair) (*pairStorageWrite, error) {
	result := &pairStorageWrite{}

	values := make(map[string]interface{})
	for _, v := range opts {
		if _, ok := allowedStoragePairs["write"]; !ok {
			continue
		}
		if _, ok := allowedStoragePairs["write"][v.Key]; !ok {
			continue
		}
		values[v.Key] = v.Value
	}
	var v interface{}
	var ok bool
	v, ok = values[types.Size]
	if ok {
		result.HasSize = true
		result.Size = v.(int64)
	}
	return result, nil
}
