// Code generated by go generate via internal/cmd/meta_gen; DO NOT EDIT.
package posixfs

import (
	"github.com/Xuanwo/storage/types"
)

// CapabilityRead    = true
// CapabilityWrite   = true
// CapabilityFile    = true
// CapabilityStream  = true
// CapabilitySegment = true
const capability = types.Capability(115)

// Capability implements Storager.Capability().
func (c *Client) Capability() types.Capability {
	return capability
}
