// Code generated by go generate via internal/cmd/meta_gen; DO NOT EDIT.
package posixfs

import (
	"github.com/Xuanwo/storage"
	"github.com/Xuanwo/storage/types"
)

// CapabilityRead    = true
// CapabilityWrite   = true
// CapabilityFile    = true
// CapabilityStream  = true
// CapabilitySegment = true
const capability = types.Capability(31)

// Capability implements Storager.Capability().
func (c *Client) Capability() types.Capability {
	return capability
}

var allowedStoragePairs = map[string]map[string]struct{}{
	storage.ActionListDir: {
		"recursive": struct{}{},
	},
}

var allowedServicePairs = map[string]map[string]struct{}{}

// IsPairAvailable implements Storager.IsPairAvailable().
func (c *Client) IsPairAvailable(action, pair string) bool {
	if _, ok := allowedStoragePairs[action]; !ok {
		return false
	}
	if _, ok := allowedStoragePairs[action][pair]; !ok {
		return false
	}
	return true
}

type pairStorageListDir struct {
	HasRecursive bool
	Recursive    bool
}

func parseStoragePairListDir(opts ...*types.Pair) (*pairStorageListDir, error) {
	result := &pairStorageListDir{}

	values := make(map[string]interface{})
	for _, v := range opts {
		if _, ok := allowedStoragePairs[storage.ActionListDir]; !ok {
			continue
		}
		if _, ok := allowedStoragePairs[storage.ActionListDir][v.Key]; !ok {
			continue
		}
		values[v.Key] = v.Value
	}
	var v interface{}
	var ok bool
	v, ok = values[types.Recursive]
	if ok {
		result.HasRecursive = true
		result.Recursive = v.(bool)
	}
	return result, nil
}
