// Code generated by go generate internal/cmd/options_gen; DO NOT EDIT.
package define

// WithMd5 will apply md5 value to Options
func WithMd5(v string) *Option {
	return &Option{
		Key:   "md5",
		Value: v,
	}
}

// WithStorageClass will apply storage_class value to Options
func WithStorageClass(v string) *Option {
	return &Option{
		Key:   "storage_class",
		Value: v,
	}
}
