name = "dropbox"


[namespace.storage]
implement = ["appender", "direr"]

[namespace.storage.new]
required = ["credential"]
optional = ["work_dir", "http_client_options"]

[namespace.storage.op.create]
optional = ["object_mode"]

[namespace.storage.op.delete]
optional = ["object_mode"]

[namespace.storage.op.list]
optional = ["list_mode"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size"]

[namespace.storage.op.stat]
optional = ["object_mode"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback"]

[infos.object.meta.upload-session-id]
type = "string"
description = "a unique identifier for the upload session, refer to https://www.dropbox.com/developers/documentation/http/documentation#files-upload_session-start"
