name = "ipfs"

[namespace.storage]
implement = ["copier", "mover", "direr", "storage_http_signer"]

[namespace.storage.new]
required = ["endpoint", "gateway"]
optional = ["work_dir"]

[namespace.storage.op.create]
optional = ["object_mode"]

[namespace.storage.op.list]
optional = ["list_mode"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback"]

[namespace.storage.op.delete]
optional = ["object_mode"]

[namespace.storage.op.stat]
optional = ["object_mode"]

[pairs.gateway]
type = "string"
description = "set storage gateway, for http(s) request purpose"

[infos.object.meta.hash]
type = "string"
description = "the CID of the file or directory"

[infos.object.meta.blocks]
type = "int"
description = "the number of files in the directory or the number of blocks that make up the file"

[infos.object.meta.cumulative_size]
type = "uint64"
description = "the size of the DAGNodes making up the file in Bytes, or the sum of the sizes of all files in the directory"

[infos.object.meta.local]
type = "bool"
description = "whether the file`s dags is fully present locally"

[infos.object.meta.with_locality]
type = "bool"
description = "whether the locality information is present"

[infos.object.meta.size_local]
type = "uint64"
description = "the cumulative size of the data present locally"
