// Code generated by go generate internal/cmd/options_gen; DO NOT EDIT.
package option

import (
	"github.com/Xuanwo/storage/types"
)

// WithChecksum will apply checksum value to Options
func WithChecksum(v string) *types.Option {
	return &types.Option{
		Key:   "checksum",
		Value: v,
	}
}

// WithLocation will apply location value to Options
func WithLocation(v string) *types.Option {
	return &types.Option{
		Key:   "location",
		Value: v,
	}
}

// WithStorageClass will apply storage_class value to Options
func WithStorageClass(v string) *types.Option {
	return &types.Option{
		Key:   "storage_class",
		Value: v,
	}
}
