package main

import (
	"log"
	"os"
	"text/template"

	"github.com/Masterminds/sprig"
	"github.com/Xuanwo/storage/types"
)

func main() {
	const filePath = "../pkg/option/options.go"

	f, err := os.Create(filePath)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	err = tmpl.Execute(f, struct {
		Data map[string]string
	}{
		types.AvailableOptions,
	})
	if err != nil {
		log.Fatal(err)
	}
}

var tmpl = template.Must(template.New("").Funcs(sprig.HermeticTxtFuncMap()).Parse(`// Code generated by go generate internal/cmd/options_gen; DO NOT EDIT.
package option

import (
	"github.com/Xuanwo/storage/types"
)

// All available options.
const (
{{- range $k, $v := .Data }}
	{{ $k | camelcase }} = "{{ $k }}"
{{- end }}
)

{{- range $k, $v := .Data }}
// With{{ $k | camelcase }} will apply {{ $k }} value to Options
func With{{ $k | camelcase }}(v {{ $v }}) *types.Option {
	return &types.Option{
		Key: {{ $k | camelcase }},
		Value: v,
	}
}
{{- end }}
`))
