name: golangci-lint
on: [push, pull_request]
jobs:
  golangci_lint:
    name: golangci_lint
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
