// Code generated by go generate via internal/cmd/meta_gen; DO NOT EDIT.
package qingstor

import (
	"github.com/Xuanwo/storage/define"
)

var allowdOptionWriteFile = map[string]struct{}{
	"md5":           struct{}{},
	"storage_class": struct{}{},
}

type optionWriteFile struct {
	HasMd5          bool
	Md5             string
	HasStorageClass bool
	StorageClass    string
}

func parseOptionWriteFile(opts ...define.Option) *optionWriteFile {
	result := &optionWriteFile{}

	values := make(map[string]interface{})
	for _, v := range opts {
		if _, ok := allowdOptionWriteFile[v.Key]; ok {
			values[v.Key] = v
		}
	}
	if v, ok := values["md5"]; ok {
		result.HasMd5 = true
		result.Md5 = v.(string)
	}
	if v, ok := values["storage_class"]; ok {
		result.HasStorageClass = true
		result.StorageClass = v.(string)
	}
	return result
}
